pipeline {
  agent any
  stages {
    stage('Upload to S3') {
      steps {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',credentialsId: '<Credientials id on Jenkins>']]) {
          sh 'aws s3 sync <path in s3> s3://<Local Relative Path>'
        }
      }
    }
  }
}